### ISSUE TITLE
Stopped working after core update

### ISSUE THREAD

**Issue by bttfw** [enes-oerdek/Home-Assistant-Helium-Integration#8]
As the Titel 😁

**Comment by liviooo** [comment]
Same here

**Comment by nict41** [comment]
Same here

**Comment by pbvdven** [comment]
i wanted to try the helium integration but its not working guess same issue 

here is some error log that i get. 

But at least its nice to see there is a new helium integration for HA. thanks for that.

Logger: homeassistant.components.sensor
Source: custom_components/helium_solana/sensors/HeliumStats.py:94
Integration: Sensor (documentation, issues) 
First occurred: 15:46:33 (20 occurrences) 
Last logged: 15:46:44

helium_solana: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/helium_solana/sensors/HeliumStats.py", line 74, in async_update
    response = await self.api.get_data()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/heliumstats.py", line 28, in get_data
    response = await asyncio.to_thread(self.http_client, self.url, None, 'GET', headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/heliumstats.py", line 19, in http_client
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://beta-api.hotspotty.net/api/v1/stats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/helium_solana/sensors/HeliumStats.py", line 94, in async_update
    _LOGGER.exception("Error retrieving helium stats from hotspotty")
    ^^^^^^^
NameError: name '_LOGGER' is not defined

**Comment by enes-oerdek** [comment]
Hello @pbvdven @liviooo @nict41 @bttfw , thanks a lot for raising this issue. I will asap debug and submit an update for this issue. I will send you more info as soon as I have any updates.

**Comment by enes-oerdek** [comment]
Sorry for the inconvenience @pbvdven @liviooo @nict41 @bttfw . Everything should work now back again. The latest update fixes the existing issue. Please install the latest update to fix this issue :) I will leave this issue open for some days, in case you have further issues related to this.

**Comment by nict41** [comment]
Hi @enes-oerdek 
Thanks so much for looking at this so fast.
Unfortunately I'm still having the same issue. I've updated the integration and done several full system reboots but still all sensors unavailable. Any suggestions?

**Comment by enes-oerdek** [comment]
Hello @nict41 if you post your wallet id here as reply or via discord to "milchtuetenente", I can debug the issue and let you know.

**Comment by nict41** [comment]
@enes-oerdek 
Thanks a million:

WC2kU67inSxEjXz5kTcv8UWKDaQktkrsYNpV2FmJP4o

**Comment by pbvdven** [comment]
@enes-oerdek, i also updated the integration to 2.4.2 but i still get a error i can setup the integration but no entities get added. its a different error then before with 2.4.1

Error:
Error adding entities for domain sensor with platform helium_solana
Error while setting up helium_solana platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'node_name'

If it helps here is my solana address 4PPtWfiDvfHktRJ5zkSwVE71N8pTEFDofzDG65x7m2mA

**Comment by bttfw** [comment]
Same for me no change

**Comment by ragman11** [comment]
Hi, After the latest update, still all Sensors unavailable..

**Comment by enes-oerdek** [comment]
@liviooo @pbvdven @bttfw @nict41 @ragman11 
Sorry again for the inconvenience. In my dev environment I missed to install the latest stable version of home assistant, which caused the regression issues. 
Could you please try again?

**Comment by pbvdven** [comment]
> @liviooo @pbvdven @bttfw @nict41 @ragman11
> Sorry again for the inconvenience. In my dev environment I missed to install the latest stable version of home assistant, which caused the regression issues.
> Could you please try again?

For me its working now. Thanks for your time to fix the issue.

**Comment by liviooo** [comment]
> > @liviooo @pbvdven @bttfw @nict41 @ragman11
> > Sorry again for the inconvenience. In my dev environment I missed to install the latest stable version of home assistant, which caused the regression issues.
> > Could you please try again?
> 
> For me its working now. Thanks for your time to fix the issue.

+1

**Comment by nict41** [comment]
Fantastic, working perfectly for me now. Really appreciate your speedy work on this

**Comment by ragman11** [comment]
> Hi, After the latest update, still all Sensors unavailable..

Thank you, working perfectly again...

**Comment by enes-oerdek** [comment]
I just published another update, which might break some of the existing configurations. Please be welcome to also join the discord thread in the helium discord:
https://discord.com/channels/404106811252408320/1118663072488366120

I try to make the updates more stable, this is hopefully the last breaking change. All upcoming changes will be delivered in a modular way.
